### ISSUE TITLE
所有的ajax请求都是canceled,什么原因呢？

### ISSUE THREAD

**Issue by gntyu** [scscms/scs-monitor#1]

**Comment by msq6323013** [comment]
devServer: {
    proxy: {
      '/api/':

**Comment by scscms** [comment]
你是不是只跑了前端而没有相应后端？
npm run dev 需要后端支持并设置代理
npm run server 只运行后端
npm run start 前后端同时运行，等同同时执行前面两条命令

**Comment by gntyu** [comment]
> 你是不是只跑了前端而没有相应后端？
> npm run dev 需要后端支持并设置代理
> npm run server 只运行后端
> npm run start 前后端同时运行，等同同时执行前面两条命令

跑了啊，npm run start 这个会报错，我就两个终端窗口分别起了前端和后端，能运行啊。代理设置是后端服务的地址，但是请求都是canceled，我看fork的那个项目都没这个问题。
